spring:
#데이터베이스 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://210.179.175.147:3306/insrbdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: micro-dev
    password: insurobo1!
#jpa 설정
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# 타임리프 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false


#swagger 라이브러리 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #스프링 시큐리티 OAuth 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d92f7ad36583ff79727bf959fce8948f
            redirect-uri: http://210.179.175.147:8080/api/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: WwwXCiaHbQPLOXMWO8DM
            client-secret: e9ZjxbTa_6
            redirect-uri: http://210.179.175.147:8080/api/oauth2/callback/naver
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Naver
            scope:
              - name
              - email
              - mobile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


#이미지 업로드 경로
file:
  path: /home/upload/

